# 1.1.numpy package






In [ ]:
#1 array creation
import numpy as np
a=np.array([1,2,3,4,5])
b=np.arange(1,10,2)
c=np.linspace(0,10,5)
d=np.zeros((3,3))
e=np.ones((3,3))
f=np.eye(3)
g=np.random.randint(1,100,size=(3,3))
print("Array a:",a)
print("Arrange b:",b)
print("Linspace c:",c)
print("Zeros d:",d)
print("Ones e:",e)
print("Identity matrix f:",f)
print("Random matrix g:",g)

Array a: [1 2 3 4 5]
Arrange b: [1 3 5 7 9]
Linspace c: [ 0.   2.5  5.   7.5 10. ]
Zeros d: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones e: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity matrix f: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random matrix g: [[44  5 91]
 [95 46 85]
 [44 50 21]]


In [2]:
#2 array properties
'''Random matrix g: [[98 19 69]
                  At   [25 36 30]
                     [ 2 58 72]]'''
print("\nShape:",g.shape)
print("Size:",g.size)
print("Data type:",g.dtype)
print("Dimension:",g.ndim)
print("Item size:",g.itemsize)


Shape: (3, 3)
Size: 9
Data type: int64
Dimension: 2
Item size: 8


In [ ]:
#3 reshape & transpose
'''Random matrix g: [[98 19 69]
                     [25 36 30]
                     [ 2 58 72]]'''
reshaped=g.reshape(1,9)
print("\nReshaped Array:",reshaped)
print("Transpose:\n",g.T)
print("Flattened:",g.flatten())


Reshaped Array: [[98 19 69 25 36 30  2 58 72]]
Transpose:
 [[98 25  2]
 [19 36 58]
 [69 30 72]]
Flattened: [98 19 69 25 36 30  2 58 72]


In [ ]:
#4 Mathematical Opertions
#Array a: [1 2 3 4 5]
print("multiply:",np.multiply(a,2))
print("square root:",np.sqrt(a))
print("power:",np.power(a,2))
print("absolute:",np.abs([-1,-2,3]))

print("Square:",np.square(a))
print("\nAdd:",np.add(a,2))
print("Subtract:",np.subtract(a,2))
print("Divide:",np.divide(a,2))

multiply: [ 2  4  6  8 10]
square root: [1.         1.41421356 1.73205081 2.         2.23606798]
power: [ 1  4  9 16 25]
absolute: [1 2 3]
Square: [ 1  4  9 16 25]

Add: [3 4 5 6 7]
Subtract: [-1  0  1  2  3]
Divide: [0.5 1.  1.5 2.  2.5]


In [ ]:
#5 statistical methods
#Array a: [1 2 3 4 5]
print("Mean:",np.mean(a))
print("Median:",np.median(a))
print("Standard Deviation:",np.std(a))
print("Variance:",np.var(a))
print("Min:",np.min(a))
print("Max:",np.max(a))
print("Sum:",np.sum(a))
print("percentile(20)",np.percentile(a,20))


Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Min: 1
Max: 5
Sum: 15
percentile(20) 1.8


In [ ]:
#7 indexing and slicing
#Array a: [1 2 3 4 5]
print("\nfirst element:",a[0])
print("slice:",a[1:4])
'''Random matrix g: [[98 19 69]
                     [25 36 30]
                     [ 2 58 72]]'''
print("2D slice:",g[0:2,1:3])


first element: 1
slice: [2 3 4]
2D slice: [[19 69]
 [36 30]]


In [ ]:
#8 boolean & conditional
'''Random matrix g: [[98 19 69]
                     [25 36 30]
                     [ 2 58 72]]'''
print("\nwhere > 50:",np.where(g>50))
print("any > 50:",np.any(g>50))
print("all > 50:",np.all(g>50))


where > 50: (array([0, 0, 2, 2]), array([0, 2, 1, 2]))
any > 50: True
all > 50: False


In [ ]:
#9 sorting & searching
#Array a: [1 2 3 4 5]
print("\n sorted array a:",np.sort(a))
print("index of max a:",np.argmax(a))
print("index of min a:",np.argmin(a))
print("unique elements:",np.unique([1,2,3,4,4]))


 sorted array a: [1 2 3 4 5]
index of max a: 4
index of min a: 0
unique elements: [1 2 3 4]


In [ ]:
#10 linear algebra
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print("\nDot product:\n",np.dot(x,y))
print("Inverse:\n",np.linalg.inv(x))


Dot product:
 [[19 22]
 [43 50]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
